resources.load([
  "./images/car.png",
  "./images/road.png",
  "./images/road2.png",
  "./images/diamond.png",
  "./images/purple_rock.png",
  "./images/box.png",
  "./images/bin.png",
  "./images/tire.png",
  "./images/cone.png",
])
resources.onReady(main);
